/* ═══════════════════════════════════════════════════════════════════════
   Entity Type System — re-exports from shared_core
   ═══════════════════════════════════════════════════════════════════════ */

export {
  type EntityType,
  type PrimitiveGeometry,
  type LightType,
  type BlendMode,
  type BillboardMode,
  type TriggerShape,
  type TriggerCondition,
  type MaterialType,
  type DoorInteractionState,
  type Vec3,
  type SpriteSheetMeta,
  type BaseEntity,
  type SpriteEntity,
  type AnimatedSpriteEntity,
  type PrimitiveEntity,
  type TextureEntity,
  type CameraEntity,
  type LightEntity,
  type SoundEntity,
  type TriggerEntity,
  type SpawnEntity,
  type DoorEntity,
  type EditorEntity,
  type ArchetypePropertyType,
  type ArchetypeObjectKind,
  type ArchetypePropertyDef,
  type ArchetypeSockets,
  type ArchetypeDef,
  type ArchetypeSchema,
  type ArchetypeInstanceEntity,
  type NestedArchetypeValue,
  type ChildEntityType,
  type ArchetypeChildDef,
  generateId,
  createDefaultTransform,
  createDefaultEntity,
  createDefaultArchetypeInstance,
  createDefaultNestedArchetypeValue,
  createDefaultChildDef,
  isNestedArchetypeValue,
  getNestedArchetypeInstances,
  composeTransforms,
  resolveArchetypeInstance,
} from '@heel-quest/shared-core';
