import { Engine } from './engine/Engine';
import { PlaceholderGenerator } from './tools/PlaceholderGenerator';
import { InitializationError, WorldLoadError } from './errors';

async function bootstrap() {
    const container = document.getElementById('game-container');
    if (!container) throw new InitializationError('Game container not found');

    const canvas = document.createElement('canvas');
    container.appendChild(canvas);

    const engine = new Engine(canvas);

    // Generate all placeholder pixel-art assets at runtime
    const generator = new PlaceholderGenerator();
    generator.generateAll(engine.getTextureManager());

    // Fetch dynamic world data generated by Editor
    try {
        const response = await fetch('/src/data/world.json');
        if (!response.ok) throw new WorldLoadError(new Error('world.json not found'));
        const worldData = await response.json();
        
        console.log(`Loaded World Project: ${worldData.projectId} with ${worldData.rooms.length} rooms`);
        
        // Map the new WorldProject format to the engine's registerRooms (which expects MapScene shape)
        // Note: the engine currently expects MapScene shape, so we format RoomData to look like MapScene 
        // Helper to extract component-based entities to properties
        const extractCameras = (entities: any[]) => {
            const cams = entities.filter(e => e.type === 'camera');
            return cams.map((cam: any, i: number) => ({
                id: cam.id || `camera_${i}`,
                position: cam.transform.position,
                rotation: {
                    x: cam.transform.rotation.x * Math.PI / 180,
                    y: cam.transform.rotation.y * Math.PI / 180,
                    z: cam.transform.rotation.z * Math.PI / 180
                },
                fov: cam.fov || 45,
                near: cam.near || 0.1,
                far: cam.far || 100,
                isDefault: cam.isDefault ?? (i === 0),
                targetLookAt: cam.lookAtTarget || ''
            }));
        };

        const extractLegacyCamera = (entities: any[]) => {
            const cam = entities.find(e => e.type === 'camera');
            if (cam) return { 
                position: cam.transform.position, 
                rotation: {
                    x: cam.transform.rotation.x * Math.PI / 180,
                    y: cam.transform.rotation.y * Math.PI / 180,
                    z: cam.transform.rotation.z * Math.PI / 180
                },
                fov: cam.fov || 45,
                near: cam.near || 0.1,
                far: cam.far || 100
            };
            return { 
                position: { x:-8, y:10, z:12 }, 
                rotation: { x: -35 * Math.PI / 180, y: 35 * Math.PI / 180, z: 0 },
                fov: 45,
                near: 0.1,
                far: 100
            };
        };

        const extractSpawnCharacter = (entities: any[]) => {
            const spawn = entities.find(e => e.type === 'spawn');
            return {
                characterSpeed: spawn?.characterSpeed,
                characterAsset: spawn?.characterAsset
            };
        };

        const mapPortals = (roomId: string) => {
            const portals: any[] = [];
            for (const door of worldData.doors) {
               if (door.room1Id === roomId && door.room2Id) {
                  portals.push({
                     id: door.id,
                     targetRoom: door.room2Id,
                     targetSpawnId: undefined,
                     position: { x: (door.points[0].x + door.points[1].x)/2, y: 0, z: (door.points[0].y + door.points[1].y)/2 },
                     boundary: { width: door.width * 2, height: 3, depth: door.width * 2 }
                  });
               } else if (door.room2Id === roomId && door.room1Id) {
                  portals.push({
                     id: door.id,
                     targetRoom: door.room1Id,
                     targetSpawnId: undefined,
                     position: { x: (door.points[0].x + door.points[1].x)/2, y: 0, z: (door.points[0].y + door.points[1].y)/2 },
                     boundary: { width: door.width * 2, height: 3, depth: door.width * 2 }
                  });
               }
            }
            return portals;
        };

        const mappedRooms = worldData.rooms.map((r: any) => {
           const legacyCam = extractLegacyCamera(r.entities);
           const spawnChar = extractSpawnCharacter(r.entities);
           return {
              id: r.id,
              name: r.name,
              ambientColor: r.ambientColor || '#ffffff',
              walkPadding: 0.5,
              spawnPoints: r.spawnPoints,
              outline: r.outline,
              entities: r.entities
                 .filter((e: any) => e.type === 'sprite' || e.type === 'animated_sprite' || e.type === 'primitive' || e.type === 'light' || e.type === 'door')
                 .map((e: any) => {
                  const result: any = {
                      entityType: e.type,
                      spriteKey: '',
                      width: e.transform.scale.x,
                      height: e.transform.scale.y,
                      position: e.transform.position,
                      rotation: e.transform.rotation,
                      scale: e.transform.scale,
                      isObstacle: false
                  };

                  if (e.type === 'primitive') {
                      result.geometryType = e.geometryType || 'cube';
                      result.color = e.color || '#808080';
                      result.opacity = e.opacity ?? 1;
                      result.isObstacle = e.isCollider ?? false;
                      result.textureSource = e.textureSource || '';
                      result.uvTilingX = e.uvTilingX ?? 1;
                      result.uvTilingY = e.uvTilingY ?? 1;
                      result.uvOffsetX = e.uvOffsetX ?? 0;
                      result.uvOffsetY = e.uvOffsetY ?? 0;
                  } else if (e.type === 'light') {
                      result.lightType = e.lightType || 'point';
                      result.lightColor = e.color || '#ffffff';
                      result.lightIntensity = e.intensity ?? 1;
                      result.lightDistance = e.distance ?? 10;
                  } else if (e.type === 'door') {
                      result.targetRoomId = e.targetRoomId || '';
                      result.targetSpawnId = e.targetSpawnId || '';
                      result.interactionState = e.interactionState || 'closed';
                      result.color = e.color || '#8B4513';
                      result.opacity = e.opacity ?? 1;
                      result.textureSource = e.textureSource || '';
                      result.uvTilingX = e.uvTilingX ?? 1;
                      result.uvTilingY = e.uvTilingY ?? 1;
                      result.uvOffsetX = e.uvOffsetX ?? 0;
                      result.uvOffsetY = e.uvOffsetY ?? 0;
                      result.isObstacle = true;
                      // Wire door entity to its portal for PortalSystem collision matching
                      result.portalId = e.worldDoorId || '';
                  } else {
                      result.spriteKey = e.textureSource || e.spriteKey || '';
                  }

                  return result;
              }),
              boundaries: {
                 floor: {
                     width: 100, depth: 100,
                     texture: 'floor_default',
                     position: { x:0, y:0, z:0 }
                 },
                 walls: [] 
              },
              portals: mapPortals(r.id),
              cameras: extractCameras(r.entities),
              cameraPosition: legacyCam.position,
              cameraRotation: legacyCam.rotation,
              cameraFov: legacyCam.fov,
              cameraNear: legacyCam.near,
              cameraFar: legacyCam.far,
              characterSpeed: spawnChar.characterSpeed,
              characterAsset: spawnChar.characterAsset
           };
        });
        
        engine.registerRooms(mappedRooms);
        engine.start();

        if (worldData.rooms.length > 0) {
            const initialRoomId = worldData.activeRoomId || worldData.rooms[0].id;
            console.log(`Starting in room: ${initialRoomId}`);
            await engine.loadRoom(initialRoomId);
        } else {
            console.warn("No rooms in world.json");
        }
    } catch(err) {
        console.error("CRITICAL ERROR: Failed loading world.json. Have you drawn a room and saved the map in the Map Editor?", err);
        // Throw visually so the developer sees it
        const div = document.createElement('div');
        div.style.color = "red";
        div.style.padding = "20px";
        div.style.fontFamily = "sans-serif";
        div.innerHTML = "<h2>Failed to load world!</h2><p>Please launch the Map Editor, draw at least one room, place a Camera and Spawn point, and click Save to export the world.json payload to the engine!</p>";
        container.appendChild(div);
    }

    console.log('Heel Quest — Engine Started');
}

bootstrap().catch(console.error);
