import { Engine } from './engine/Engine';
import { PlaceholderGenerator } from './tools/PlaceholderGenerator';
import { InitializationError, WorldLoadError } from './errors';
import { WorldLoader } from './loaders/WorldLoader';

interface EditorPreviewMessage {
    type: 'heelquest-editor-preview-sync';
    roomId: string | null;
    cameraId: string | null;
    camera: {
        position: { x: number; y: number; z: number };
        rotation: { x: number; y: number; z: number };
        fov: number;
        near: number;
        far: number;
    } | null;
}

async function loadWorldIntoEngine(engine: Engine) {
    const response = await fetch('/src/data/world.json');
    if (!response.ok) throw new WorldLoadError(new Error('world.json not found'));
    const worldData = await response.json();

    const tm = engine.getTextureManager();
    const { rooms: mappedRooms, initialRoomId, sheetMeta } = await WorldLoader.load(worldData, tm);

    engine.getRoomManager().setSheetMeta(sheetMeta);
    engine.registerRooms(mappedRooms);

    return { initialRoomId };
}

async function bootstrap() {
    const container = document.getElementById('game-container');
    if (!container) throw new InitializationError('Game container not found');

    const canvas = document.createElement('canvas');
    container.appendChild(canvas);

    const engine = new Engine(canvas);

    // Generate all placeholder pixel-art assets at runtime
    const generator = new PlaceholderGenerator();
    generator.generateAll(engine.getTextureManager());

    const isDevHost = ['localhost', '127.0.0.1'].includes(window.location.hostname) || window.location.port === '3000';
    const isEditorPreview = isDevHost && new URLSearchParams(window.location.search).get('editorPreview') === '1';

    // Fetch dynamic world data generated by Editor
    try {
        const { initialRoomId } = await loadWorldIntoEngine(engine);

        if (initialRoomId) {
            await engine.loadRoom(initialRoomId);
        } else {
            console.warn('No rooms in world.json');
        }

        // Start the loop only after the initial room is loaded.
        // This ensures shader warmup runs before the first visible frame.
        engine.start();
    } catch(err) {
        console.error("CRITICAL ERROR: Failed loading world.json. Have you drawn a room and saved the map in the Map Editor?", err);
        const div = document.createElement('div');
        div.style.color = "red";
        div.style.padding = "20px";
        div.style.fontFamily = "sans-serif";
        div.innerHTML = "<h2>Failed to load world!</h2><p>Please launch the Map Editor, draw at least one room, place a Camera and Spawn point, and click Save to export the world.json payload to the engine!</p>";
        container.appendChild(div);
    }

    if (isEditorPreview) {
        const expectedOrigin = `${window.location.protocol}//${window.location.hostname}:3001`;
        let lastRoomId: string | null = null;

        window.addEventListener('message', async (event: MessageEvent<EditorPreviewMessage>) => {
            if (event.origin !== expectedOrigin) return;
            const data = event.data;
            if (!data || data.type !== 'heelquest-editor-preview-sync') return;

            try {
                if (data.roomId && data.roomId !== lastRoomId) {
                    await loadWorldIntoEngine(engine);
                    await engine.loadRoom(data.roomId);
                    lastRoomId = data.roomId;
                }

                const cameraSystem = engine.getCameraSystem();
                if (cameraSystem && data.cameraId) {
                    cameraSystem.switchCameraBySourceId(data.cameraId);
                }
                if (cameraSystem && data.camera) {
                    cameraSystem.applyPreviewOverride(data.camera);
                }
            } catch (error) {
                console.error('Editor preview sync failed:', error);
            }
        });
    }

}

bootstrap().catch(console.error);
